// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UsersService.Infrastructure.Repositories;

#nullable disable

namespace UsersService.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UsersService.Domain.Entities.BlackToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BlackTokens");
                });

            modelBuilder.Entity("UsersService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Created = new DateTime(2026, 3, 31, 14, 40, 41, 451, DateTimeKind.Utc).AddTicks(4770),
                            Email = "ageev@gmail.com",
                            FirstName = "Леша",
                            HashPassword = "$2a$11$8VKnCG5FEC0AieuMTDplsOuVjch35WTrL.lmvJ5aQ7F/RQeC2svtO",
                            LastName = "Агеев",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Created = new DateTime(2026, 3, 31, 14, 40, 41, 451, DateTimeKind.Utc).AddTicks(4770),
                            Email = "budaeva@gmail.com",
                            FirstName = "Заята",
                            HashPassword = "$2a$11$FzevHL6vVUo5h/XPus/erODBeGB.3yye2egUyQynoPttkSsgoySKa",
                            LastName = "Будаева",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Created = new DateTime(2026, 3, 31, 14, 40, 41, 451, DateTimeKind.Utc).AddTicks(4770),
                            Email = "yaganova@gmail.com",
                            FirstName = "Маргарита",
                            HashPassword = "$2a$11$HnIKl653ofLi.PDwIAnu..tVt1nP.3CFckgs9.V9TvKaaM7lsMJZW",
                            LastName = "Яганова",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Created = new DateTime(2026, 3, 31, 14, 40, 41, 451, DateTimeKind.Utc).AddTicks(4770),
                            Email = "ilyashova@gmail.com",
                            FirstName = "Настя",
                            HashPassword = "$2a$11$HcuxDPVHqQy0czV2vs4w7OdL2BEiQANc7UJ5rBG5t8syZBBOPrBA2",
                            LastName = "Ильяшова",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Created = new DateTime(2026, 3, 31, 14, 40, 41, 451, DateTimeKind.Utc).AddTicks(4770),
                            Email = "shakirov@gmail.com",
                            FirstName = "Ирек",
                            HashPassword = "$2a$11$BFeT8egiAf5AY1M65Tf5suoWhEaYPpHuMqawF2kWIOi/ScFXyWfCC",
                            LastName = "Шакиров",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Created = new DateTime(2026, 3, 31, 14, 40, 41, 451, DateTimeKind.Utc).AddTicks(4770),
                            Email = "mescheryakov@gmail.com",
                            FirstName = "Сергей",
                            HashPassword = "$2a$11$14tp6eaTuZCC38eTroKpuO06VKPukr3wjtETn04PvIt5ROP/eorQS",
                            LastName = "Мещеряков",
                            Role = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
