// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YoungConService.Infrastructure.Repositories;

#nullable disable

namespace YoungConService.Migrations
{
    [DbContext(typeof(YoungConDbContext))]
    [Migration("20260407142236_UpdateSpeakerAvatarSeedData")]
    partial class UpdateSpeakerAvatarSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventSpeakers", b =>
                {
                    b.Property<Guid>("EventsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpeakersId")
                        .HasColumnType("uuid");

                    b.HasKey("EventsId", "SpeakersId");

                    b.HasIndex("SpeakersId");

                    b.ToTable("EventSpeakers", (string)null);

                    b.HasData(
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000001"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000002"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000003"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000004"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000005"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000006"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000007"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000008"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000009"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-00000000000a"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-00000000000a")
                        });
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.Property<Guid>("LikedEventsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LikedEventsId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLikedEvents", (string)null);
                });

            modelBuilder.Entity("UserAchievments", b =>
                {
                    b.Property<Guid>("AchievmentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AchievmentsId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievments", (string)null);

                    b.HasData(
                        new
                        {
                            AchievmentsId = new Guid("f6000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            AchievmentsId = new Guid("f6000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            AchievmentsId = new Guid("f6000000-0000-0000-0000-000000000003"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Achievment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Achievments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000001"),
                            Color = "#2563EB",
                            Description = "Первый вход в приложение",
                            Icon = "https://storage.yandexcloud.net/youngcon/free-icon-bird-roadrunner-shape-47127%20(1).png",
                            Name = "КВЕСТ ПРОЙДЕН"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000002"),
                            Color = "#7C3AED",
                            Description = "Просмотрено 5 событий",
                            Icon = "https://storage.yandexcloud.net/youngcon/free-icon-bird-roadrunner-shape-47127%20(1).png",
                            Name = "КОФЕМАН"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000003"),
                            Color = "#DC2626",
                            Description = "Добавлен первый фестиваль в избранное",
                            Icon = "https://storage.yandexcloud.net/youngcon/free-icon-bird-roadrunner-shape-47127%20(1).png",
                            Name = "НЕТВОРКЕР"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000004"),
                            Color = "#16A34A",
                            Description = "Проведен весь день на фестивале (11:00–23:00)",
                            Icon = "https://storage.yandexcloud.net/youngcon/free-icon-bird-roadrunner-shape-47127%20(1).png",
                            Name = "ЦЕЛЫЙ ДЕНЬ"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000005"),
                            Color = "#EA580C",
                            Description = "Прослушано 3 доклада",
                            Icon = "https://storage.yandexcloud.net/youngcon/free-icon-bird-roadrunner-shape-47127%20(1).png",
                            Name = "ОФФЕР В КАРМАНЕ!"
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.BlackToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("BlackTokens", (string)null);
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StreamURL")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000001"),
                            Category = "Пленарный доклад",
                            Description = "Торжественное открытие конференции. Обзор платформы, основные возможности и план развития",
                            EndDateTime = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            StreamURL = "https://www.youtube.com/watch?v=TdnLjukE6Ws&list=PLXtiZNKIobF6Nj5wq6viExCgXELPZ55dA&index=1",
                            Title = "Вводная по платформе",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000002"),
                            Category = "Доклад",
                            Description = "Первая часть углубленного курса по Swift. Изучаем продвинутые концепции и лучшие практики программирования на Swift",
                            EndDateTime = new DateTime(2026, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            StreamURL = "https://www.youtube.com/watch?v=C2k_GzjdDQk&list=PLXtiZNKIobF6Nj5wq6viExCgXELPZ55dA&index=2",
                            Title = "Advanced Swift programming Part 1",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000003"),
                            Category = "Кейс",
                            Description = "Вторая часть углубленного курса по Swift. Продолжение изучения сложных паттернов и оптимизации кода",
                            EndDateTime = new DateTime(2026, 6, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            StreamURL = "https://www.youtube.com/watch?v=XDZal1OUbrU&list=PLXtiZNKIobF6Nj5wq6viExCgXELPZ55dA&index=3",
                            Title = "Advanced Swift programming Part 2",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000004"),
                            Category = "Воркшоп",
                            Description = "Введение в SwiftUI. Основы построения пользовательских интерфейсов с использованием декларативного подхода",
                            EndDateTime = new DateTime(2026, 6, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            StreamURL = "https://www.youtube.com/watch?v=NZ46DBOaUzc&list=PLXtiZNKIobF6Nj5wq6viExCgXELPZ55dA&index=4",
                            Title = "Basic SwiftUI",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000005"),
                            Category = "Доклад",
                            Description = "Продвинутые техники в SwiftUI. Работа со сложными состояниями, анимациями и оптимизацией производительности",
                            EndDateTime = new DateTime(2026, 6, 25, 13, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            StreamURL = "https://www.youtube.com/watch?v=FPJNTfR6_J8&list=PLXtiZNKIobF6Nj5wq6viExCgXELPZ55dA&index=5",
                            Title = "Advanced SwiftUI",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000006"),
                            Category = "Кейс",
                            Description = "Классический подход к разработке интерфейсов на iOS. Основные компоненты и практические примеры использования UIKit",
                            EndDateTime = new DateTime(2026, 6, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 13, 0, 0, 0, DateTimeKind.Utc),
                            StreamURL = "https://www.youtube.com/watch?v=1PdibPZQu7w&list=PLXtiZNKIobF6Nj5wq6viExCgXELPZ55dA&index=6",
                            Title = "UIKit",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000007"),
                            Category = "Доклад",
                            Description = "Паттерны архитектуры приложений iOS. MVVM, VIPER, Clean Architecture и их применение в реальных проектах",
                            EndDateTime = new DateTime(2026, 6, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            StreamURL = "https://www.youtube.com/watch?v=qhG36NquE8M&list=PLXtiZNKIobF6Nj5wq6viExCgXELPZ55dA&index=7",
                            Title = "Архитектура",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000008"),
                            Category = "Воркшоп",
                            Description = "Инструменты разработки для iOS. Xcode, системы управления зависимостями и оптимизация workflow разработчика",
                            EndDateTime = new DateTime(2026, 6, 25, 16, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            StreamURL = "https://www.youtube.com/watch?v=kJtf5InGOME&list=PLXtiZNKIobF6Nj5wq6viExCgXELPZ55dA&index=8",
                            Title = "IDE, Toolchain, Cocoapods/SPM",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000009"),
                            Category = "Панель",
                            Description = "Основы многопоточности в Swift. Главная очередь, фоновые потоки и синхронизация данных",
                            EndDateTime = new DateTime(2026, 6, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 16, 0, 0, 0, DateTimeKind.Utc),
                            StreamURL = "https://www.youtube.com/watch?v=2sktj5cL4wg&list=PLXtiZNKIobF6Nj5wq6viExCgXELPZ55dA&index=9",
                            Title = "Basic Concurrency",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-00000000000a"),
                            Category = "Вопросы и ответы",
                            Description = "Продвинутые концепции многопоточности в Swift. Async/await, actors и обработка ошибок при асинхронной работе",
                            EndDateTime = new DateTime(2026, 6, 25, 20, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            StreamURL = "https://www.youtube.com/watch?v=MKgtXIStCfk&list=PLXtiZNKIobF6Nj5wq6viExCgXELPZ55dA&index=10",
                            Title = "Advanced Concurrency",
                            ZoneId = new Guid("f3000000-0000-0000-0000-00000000000a")
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Festival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Festivals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Description = "Главный фестиваль про технологии, карьеру и сообщества",
                            EndDateTime = new DateTime(2026, 6, 25, 20, 0, 0, 0, DateTimeKind.Utc),
                            StartDateTime = new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            Title = "YoungCon 2026"
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MapURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2000000-0000-0000-0000-000000000001"),
                            MapURL = "https://storage.yandexcloud.net/youngcon/FirstFloor.png",
                            Title = "1 этаж"
                        },
                        new
                        {
                            Id = new Guid("f2000000-0000-0000-0000-000000000002"),
                            MapURL = "https://storage.yandexcloud.net/youngcon/SecondFloor.png",
                            Title = "2 этаж"
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Speaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000001"),
                            AvatarURL = "https://storage.yandexcloud.net/youngcon/photo_2026-04-07%2017.09.31.jpeg",
                            Bio = "15 лет развивает веб-платформы и клиентские архитектуры",
                            FullName = "Алексей Агеев",
                            Job = "Техлид команды мобильной разработки в Межгороде"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000002"),
                            AvatarURL = "https://disk.yandex.ru/i/UQpqThhyd6LYiw",
                            Bio = "Создает мобильные приложения для миллионов пользователей",
                            FullName = "Андрей Сикерин",
                            Job = "Техлид мобильной разработки"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000003"),
                            AvatarURL = "https://storage.yandexcloud.net/youngcon/photo_2026-04-07%2017.09.25.jpeg",
                            Bio = "Проектирует рекомендательные и поисковые модели",
                            FullName = "Мария Журавлева",
                            Job = "HR manager"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000004"),
                            AvatarURL = "https://storage.yandexcloud.net/youngcon/photo_2026-04-07%2017.08.30.jpeg",
                            Bio = "Автоматизирует облачную инфраструктуру и релизы",
                            FullName = "Илья Соловьев",
                            Job = "DevOps-архитектор"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000005"),
                            AvatarURL = "https://storage.yandexcloud.net/youngcon/photo_2026-04-07%2017.09.12.jpeg",
                            Bio = "Специализируется на распределенных сервисах",
                            FullName = "Тимур Долозаткин",
                            Job = "iOS инженер Yandex Go"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000006"),
                            AvatarURL = "https://storage.yandexcloud.net/youngcon/photo_2026-04-07%2017.09.38.jpeg",
                            Bio = "Ведет кросс-функциональные продуктовые команды",
                            FullName = "Дима Деларю",
                            Job = "iOS-разработчик Yandex Go"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000007"),
                            AvatarURL = "https://storage.yandexcloud.net/youngcon/photo_2026-04-07%2017.09.44.jpeg",
                            Bio = "Проектирует интерфейсы на основе пользовательских данных",
                            FullName = "Антон Таранов",
                            Job = "UX-дизайнер"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000008"),
                            AvatarURL = "https://storage.yandexcloud.net/youngcon/photo_2026-04-07%2017.08.55.jpeg",
                            Bio = "Занимается безопасностью приложений и API",
                            FullName = "Никикта Леванов",
                            Job = "iOS-разработчик Yandex Go"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000009"),
                            AvatarURL = "https://storage.yandexcloud.net/youngcon/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%C2%A0%E2%80%94%202026-04-07%20%D0%B2%C2%A017.10.48.png",
                            Bio = "Помогает командам на ранней стадии роста",
                            FullName = "Анастасия Талмазан",
                            Job = "Yandex Go SuperApp"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-00000000000a"),
                            AvatarURL = "https://disk.yandex.ru/i/UQpqThhyd6LYiw",
                            Bio = "Развивает инженерные и продуктовые сообщества",
                            FullName = "Ольга Андреева",
                            Job = "Лид комьюнити"
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ageev@gmail.com",
                            FirstName = "Леша",
                            HashPassword = "$2a$11$gCAufVWeez3MDd8oFZQ7tONAwMSZAbvLeMXyNOYHOB1Ss5/n/eZXy",
                            LastName = "Агеев",
                            Major = "IOS",
                            QrCode = "QR-11111111",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "budaeva@gmail.com",
                            FirstName = "Заята",
                            HashPassword = "$2a$11$UQXeDxqmj0EWcvsKyox8Y..KyqJv2k4aLVuc5NGmoqjvijPDqn9oy",
                            LastName = "Будаева",
                            Major = "Backend",
                            QrCode = "QR-33333333",
                            Role = "Client"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "yaganova@gmail.com",
                            FirstName = "Маргарита",
                            HashPassword = "$2a$11$Ob5I3TDKDEgWrF1adZjSx.p5FwWmZzpujQ6/VHuIFU3CfJhhLUTWK",
                            LastName = "Яганова",
                            Major = "DevOps",
                            QrCode = "QR-44444444",
                            Role = "Client"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ilyashova@gmail.com",
                            FirstName = "Настя",
                            HashPassword = "$2a$11$vNqPxkGEGmhG1z.8ZR0vgu.AgFqKP84V12XHleGmbCdK4ACXOMQJu",
                            LastName = "Ильяшова",
                            Major = "Flutter",
                            QrCode = "QR-55555555",
                            Role = "Client"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "shakirov@gmail.com",
                            FirstName = "Ирек",
                            HashPassword = "$2a$11$YXLD4kx1Ig91fzeqPDCHheUfYfF//2BSZcGcorZ0dvZtOJYbAX5xa",
                            LastName = "Шакиров",
                            Major = "ML",
                            QrCode = "QR-66666666",
                            Role = "Client"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mescheryakov@gmail.com",
                            FirstName = "Сергей",
                            HashPassword = "$2a$11$gXyWzFVta14QE2rumahQKeEtwwERMEAuWhSOgbl9c0Lg44kcI3amq",
                            LastName = "Мещеряков",
                            Major = "Android",
                            QrCode = "QR-77777777",
                            Role = "Client"
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CoordX")
                        .HasColumnType("double precision");

                    b.Property<double>("CoordY")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000001"),
                            Color = "#2563EB",
                            CoordX = 0.66000000000000003,
                            CoordY = 0.47999999999999998,
                            Description = "Ключевые доклады и открытие",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000001"),
                            Icon = "https://disk.yandex.ru/i/iKkOIrUSoGj94g",
                            Title = "Главная сцена"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000002"),
                            Color = "#7C3AED",
                            CoordX = 0.22,
                            CoordY = 0.11,
                            Description = "Практические сессии и разборы",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Icon = "https://disk.yandex.ru/i/dpqf86-EPl3LZQ",
                            Title = "Зал воркшопов"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000003"),
                            Color = "#059669",
                            CoordX = 0.25,
                            CoordY = 0.35999999999999999,
                            Description = "Консультации и карьерные треки",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Icon = "https://disk.yandex.ru/i/Brxe_BOEQLs4Uw",
                            Title = "Карьерная зона"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000004"),
                            Color = "#DC2626",
                            CoordX = 0.52000000000000002,
                            CoordY = 0.080000000000000002,
                            Description = "Демо и стенды по ML",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000001"),
                            Icon = "https://disk.yandex.ru/i/Brxe_BOEQLs4Uw",
                            Title = "Лаборатория ИИ"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000005"),
                            Color = "#EA580C",
                            CoordX = 0.78000000000000003,
                            CoordY = 0.11,
                            Description = "iOS и Android практики",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Icon = "https://disk.yandex.ru/i/wJm1eOGLzPXgKA",
                            Title = "Мобильная точка"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000006"),
                            Color = "#0F766E",
                            CoordX = 0.17999999999999999,
                            CoordY = 0.81999999999999995,
                            Description = "Серверные технологии и архитектура",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000001"),
                            Icon = "https://disk.yandex.ru/i/Mq_B4ltBwXqERA",
                            Title = "Бэкенд-комната"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000007"),
                            Color = "#BE185D",
                            CoordX = 0.71999999999999997,
                            CoordY = 0.81999999999999995,
                            Description = "UX, интерфейсы и прототипы",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Icon = "https://disk.yandex.ru/i/NoBvNU5C1kyYHA",
                            Title = "Дизайн-уголок"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000008"),
                            Color = "#334155",
                            CoordX = 0.71999999999999997,
                            CoordY = 0.85999999999999999,
                            Description = "Безопасная разработка и лучшие практики",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000001"),
                            Icon = "https://disk.yandex.ru/i/SRL4it0fUb1Vyg",
                            Title = "Хаб безопасности"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000009"),
                            Color = "#4F46E5",
                            CoordX = 0.75,
                            CoordY = 0.44,
                            Description = "Питчи, гипотезы и рост",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Icon = "https://disk.yandex.ru/i/vuHGvBAe5txuRAl",
                            Title = "Стартап-площадка"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-00000000000a"),
                            Color = "#16A34A",
                            CoordX = 0.17999999999999999,
                            CoordY = 0.23000000000000001,
                            Description = "Нетворкинг и вопросы экспертам",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000001"),
                            Icon = "https://disk.yandex.ru/i/6MvK-ECffChbPg",
                            Title = "Комьюнити-зона"
                        });
                });

            modelBuilder.Entity("EventSpeakers", b =>
                {
                    b.HasOne("YoungConService.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoungConService.Domain.Entities.Speaker", null)
                        .WithMany()
                        .HasForeignKey("SpeakersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.HasOne("YoungConService.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("LikedEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoungConService.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserAchievments", b =>
                {
                    b.HasOne("YoungConService.Domain.Entities.Achievment", null)
                        .WithMany()
                        .HasForeignKey("AchievmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoungConService.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Event", b =>
                {
                    b.HasOne("YoungConService.Domain.Entities.Festival", "Festival")
                        .WithMany("Events")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoungConService.Domain.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Zone", b =>
                {
                    b.HasOne("YoungConService.Domain.Entities.Floor", "Floor")
                        .WithMany("Zones")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Festival", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Floor", b =>
                {
                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
