// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YoungConService.Infrastructure.Repositories;

#nullable disable

namespace YoungConService.Migrations
{
    [DbContext(typeof(YoungConDbContext))]
    [Migration("20260402084445_RefreshSeedData")]
    partial class RefreshSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AchievmentUser", b =>
                {
                    b.Property<Guid>("AchievmentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AchievmentsId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievments", (string)null);
                });

            modelBuilder.Entity("EventSpeakers", b =>
                {
                    b.Property<Guid>("EventsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpeakersId")
                        .HasColumnType("uuid");

                    b.HasKey("EventsId", "SpeakersId");

                    b.HasIndex("SpeakersId");

                    b.ToTable("EventSpeakers", (string)null);

                    b.HasData(
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000001"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000002"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000003"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000004"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000005"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000006"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000007"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000008"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-000000000009"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            EventsId = new Guid("f5000000-0000-0000-0000-00000000000a"),
                            SpeakersId = new Guid("f4000000-0000-0000-0000-00000000000a")
                        });
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.Property<Guid>("LikedEventsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LikedEventsId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLikedEvents", (string)null);
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Achievment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Achievments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000001"),
                            Color = "#2563EB",
                            Description = "Первый вход в приложение",
                            Icon = "star.fill",
                            Name = "Первый вход"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000002"),
                            Color = "#7C3AED",
                            Description = "Просмотрено 5 событий",
                            Icon = "safari.fill",
                            Name = "Исследователь"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000003"),
                            Color = "#DC2626",
                            Description = "Добавлен первый фестиваль в избранное",
                            Icon = "heart.fill",
                            Name = "Фестивальный фанат"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000004"),
                            Color = "#16A34A",
                            Description = "Посещено 3 зоны общения",
                            Icon = "person.3.fill",
                            Name = "Нетворкер"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000005"),
                            Color = "#EA580C",
                            Description = "Прослушано 3 доклада",
                            Icon = "mic.fill",
                            Name = "Внимательный слушатель"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000006"),
                            Color = "#0F766E",
                            Description = "Участие в 2 воркшопах",
                            Icon = "wrench.and.screwdriver.fill",
                            Name = "Герой воркшопов"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000007"),
                            Color = "#334155",
                            Description = "Пройден трек по безопасности",
                            Icon = "lock.shield.fill",
                            Name = "Безопасный подход"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000008"),
                            Color = "#BE185D",
                            Description = "Посещение продуктовой сессии",
                            Icon = "lightbulb.fill",
                            Name = "Продуктовое мышление"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-000000000009"),
                            Color = "#4F46E5",
                            Description = "Посещение дизайн-зоны",
                            Icon = "paintpalette.fill",
                            Name = "Чувство дизайна"
                        },
                        new
                        {
                            Id = new Guid("f6000000-0000-0000-0000-00000000000a"),
                            Color = "#059669",
                            Description = "Полный день на фестивале",
                            Icon = "calendar.badge.clock",
                            Name = "Целый день"
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.BlackToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("BlackTokens", (string)null);
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000001"),
                            Category = "Пленарный доклад",
                            Description = "Торжественное открытие фестиваля",
                            EndDateTime = new DateTime(2026, 6, 25, 9, 30, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 6, 25, 8, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Открывающий доклад",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000002"),
                            Category = "Доклад",
                            Description = "Тренды и инструменты мобильной экосистемы",
                            EndDateTime = new DateTime(2026, 7, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 7, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Состояние мобильной разработки",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000003"),
                            Category = "Кейс",
                            Description = "Практика внедрения моделей в продукты",
                            EndDateTime = new DateTime(2026, 7, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 7, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            Title = "ML в продакшене",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000004"),
                            Category = "Воркшоп",
                            Description = "Подходы к стабильным релизам",
                            EndDateTime = new DateTime(2026, 7, 16, 13, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 7, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Шаблоны CI/CD",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000005"),
                            Category = "Доклад",
                            Description = "Проектирование отказоустойчивых интерфейсов",
                            EndDateTime = new DateTime(2026, 7, 23, 14, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 7, 23, 13, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Надежные API",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000006"),
                            Category = "Кейс",
                            Description = "Как находить и проверять гипотезы",
                            EndDateTime = new DateTime(2026, 7, 30, 15, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 7, 30, 14, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Поиск продуктовой ценности",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000007"),
                            Category = "Доклад",
                            Description = "Системный подход к интерфейсам",
                            EndDateTime = new DateTime(2026, 8, 6, 12, 30, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 8, 6, 11, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Дизайн-системы",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000008"),
                            Category = "Воркшоп",
                            Description = "Безопасная разработка на каждом этапе",
                            EndDateTime = new DateTime(2026, 8, 13, 13, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 8, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Безопасность по умолчанию",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-000000000009"),
                            Category = "Панель",
                            Description = "Типичные ошибки ранних стадий",
                            EndDateTime = new DateTime(2026, 8, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 8, 20, 13, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Ошибки стартапов",
                            ZoneId = new Guid("f3000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("f5000000-0000-0000-0000-00000000000a"),
                            Category = "Вопросы и ответы",
                            Description = "Вопросы и ответы с экспертами",
                            EndDateTime = new DateTime(2026, 8, 27, 17, 0, 0, 0, DateTimeKind.Utc),
                            FestivalId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            StartDateTime = new DateTime(2026, 8, 27, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Открытый микрофон",
                            ZoneId = new Guid("f3000000-0000-0000-0000-00000000000a")
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Festival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Festivals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Description = "Главный фестиваль про технологии, карьеру и сообщества",
                            EndDateTime = new DateTime(2026, 6, 25, 20, 0, 0, 0, DateTimeKind.Utc),
                            StartDateTime = new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            Title = "YoungCon 2026"
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MapURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2000000-0000-0000-0000-000000000001"),
                            MapURL = "https://youngcon.local/maps/floor-1",
                            Title = "1 этаж"
                        },
                        new
                        {
                            Id = new Guid("f2000000-0000-0000-0000-000000000002"),
                            MapURL = "https://youngcon.local/maps/floor-2",
                            Title = "2 этаж"
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Speaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000001"),
                            AvatarURL = "https://youngcon.local/avatars/speaker-1.png",
                            Bio = "15 лет развивает веб-платформы и клиентские архитектуры",
                            FullName = "Алексей Смирнов",
                            Job = "Старший фронтенд-инженер"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000002"),
                            AvatarURL = "https://youngcon.local/avatars/speaker-2.png",
                            Bio = "Создает мобильные приложения для миллионов пользователей",
                            FullName = "Мария Петрова",
                            Job = "Техлид мобильной разработки"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000003"),
                            AvatarURL = "https://youngcon.local/avatars/speaker-3.png",
                            Bio = "Проектирует рекомендательные и поисковые модели",
                            FullName = "Иван Волков",
                            Job = "ML-инженер"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000004"),
                            AvatarURL = "https://youngcon.local/avatars/speaker-4.png",
                            Bio = "Автоматизирует облачную инфраструктуру и релизы",
                            FullName = "Елена Сокол",
                            Job = "DevOps-архитектор"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000005"),
                            AvatarURL = "https://youngcon.local/avatars/speaker-5.png",
                            Bio = "Специализируется на распределенных сервисах",
                            FullName = "Никита Орлов",
                            Job = "Бэкенд-инженер"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000006"),
                            AvatarURL = "https://youngcon.local/avatars/speaker-6.png",
                            Bio = "Ведет кросс-функциональные продуктовые команды",
                            FullName = "Анна Белова",
                            Job = "Продакт-менеджер"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000007"),
                            AvatarURL = "https://youngcon.local/avatars/speaker-7.png",
                            Bio = "Проектирует интерфейсы на основе пользовательских данных",
                            FullName = "Дмитрий Егоров",
                            Job = "UX-дизайнер"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000008"),
                            AvatarURL = "https://youngcon.local/avatars/speaker-8.png",
                            Bio = "Занимается безопасностью приложений и API",
                            FullName = "София Медведева",
                            Job = "Инженер по безопасности"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-000000000009"),
                            AvatarURL = "https://youngcon.local/avatars/speaker-9.png",
                            Bio = "Помогает командам на ранней стадии роста",
                            FullName = "Павел Зорин",
                            Job = "Ментор стартапов"
                        },
                        new
                        {
                            Id = new Guid("f4000000-0000-0000-0000-00000000000a"),
                            AvatarURL = "https://youngcon.local/avatars/speaker-10.png",
                            Bio = "Развивает инженерные и продуктовые сообщества",
                            FullName = "Ольга Андреева",
                            Job = "Лид комьюнити"
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ageev@gmail.com",
                            FirstName = "Леша",
                            HashPassword = "$2a$11$gCAufVWeez3MDd8oFZQ7tONAwMSZAbvLeMXyNOYHOB1Ss5/n/eZXy",
                            LastName = "Агеев",
                            Major = "Mobile",
                            QrCode = "QR-11111111",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "budaeva@gmail.com",
                            FirstName = "Заята",
                            HashPassword = "$2a$11$UQXeDxqmj0EWcvsKyox8Y..KyqJv2k4aLVuc5NGmoqjvijPDqn9oy",
                            LastName = "Будаева",
                            Major = "ML",
                            QrCode = "QR-33333333",
                            Role = "Client"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "yaganova@gmail.com",
                            FirstName = "Маргарита",
                            HashPassword = "$2a$11$Ob5I3TDKDEgWrF1adZjSx.p5FwWmZzpujQ6/VHuIFU3CfJhhLUTWK",
                            LastName = "Яганова",
                            Major = "DevOps",
                            QrCode = "QR-44444444",
                            Role = "Client"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ilyashova@gmail.com",
                            FirstName = "Настя",
                            HashPassword = "$2a$11$vNqPxkGEGmhG1z.8ZR0vgu.AgFqKP84V12XHleGmbCdK4ACXOMQJu",
                            LastName = "Ильяшова",
                            Major = "Frontend",
                            QrCode = "QR-55555555",
                            Role = "Client"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "shakirov@gmail.com",
                            FirstName = "Ирек",
                            HashPassword = "$2a$11$YXLD4kx1Ig91fzeqPDCHheUfYfF//2BSZcGcorZ0dvZtOJYbAX5xa",
                            LastName = "Шакиров",
                            Major = "Frontend",
                            QrCode = "QR-66666666",
                            Role = "Client"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Created = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mescheryakov@gmail.com",
                            FirstName = "Сергей",
                            HashPassword = "$2a$11$gXyWzFVta14QE2rumahQKeEtwwERMEAuWhSOgbl9c0Lg44kcI3amq",
                            LastName = "Мещеряков",
                            Major = "Mobile",
                            QrCode = "QR-77777777",
                            Role = "Client"
                        });
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000001"),
                            Color = "#2563EB",
                            Description = "Ключевые доклады и открытие",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000001"),
                            Icon = "sparkles.rectangle.stack.fill",
                            Title = "Главная сцена"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000002"),
                            Color = "#7C3AED",
                            Description = "Практические сессии и разборы",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Icon = "hammer.fill",
                            Title = "Зал воркшопов"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000003"),
                            Color = "#059669",
                            Description = "Консультации и карьерные треки",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Icon = "briefcase.fill",
                            Title = "Карьерная зона"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000004"),
                            Color = "#DC2626",
                            Description = "Демо и стенды по ML",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000001"),
                            Icon = "brain.head.profile",
                            Title = "Лаборатория ИИ"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000005"),
                            Color = "#EA580C",
                            Description = "iOS и Android практики",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Icon = "iphone.gen3",
                            Title = "Мобильная точка"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000006"),
                            Color = "#0F766E",
                            Description = "Серверные технологии и архитектура",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000001"),
                            Icon = "server.rack",
                            Title = "Бэкенд-комната"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000007"),
                            Color = "#BE185D",
                            Description = "UX, интерфейсы и прототипы",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Icon = "paintpalette.fill",
                            Title = "Дизайн-уголок"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000008"),
                            Color = "#334155",
                            Description = "Безопасная разработка и лучшие практики",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000001"),
                            Icon = "shield.lefthalf.filled",
                            Title = "Хаб безопасности"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-000000000009"),
                            Color = "#4F46E5",
                            Description = "Питчи, гипотезы и рост",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000002"),
                            Icon = "paperplane.fill",
                            Title = "Стартап-площадка"
                        },
                        new
                        {
                            Id = new Guid("f3000000-0000-0000-0000-00000000000a"),
                            Color = "#16A34A",
                            Description = "Нетворкинг и вопросы экспертам",
                            FloorId = new Guid("f2000000-0000-0000-0000-000000000001"),
                            Icon = "person.3.fill",
                            Title = "Комьюнити-зона"
                        });
                });

            modelBuilder.Entity("AchievmentUser", b =>
                {
                    b.HasOne("YoungConService.Domain.Entities.Achievment", null)
                        .WithMany()
                        .HasForeignKey("AchievmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoungConService.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventSpeakers", b =>
                {
                    b.HasOne("YoungConService.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoungConService.Domain.Entities.Speaker", null)
                        .WithMany()
                        .HasForeignKey("SpeakersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventUser", b =>
                {
                    b.HasOne("YoungConService.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("LikedEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoungConService.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Event", b =>
                {
                    b.HasOne("YoungConService.Domain.Entities.Festival", "Festival")
                        .WithMany("Events")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoungConService.Domain.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Zone", b =>
                {
                    b.HasOne("YoungConService.Domain.Entities.Floor", "Floor")
                        .WithMany("Zones")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Festival", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("YoungConService.Domain.Entities.Floor", b =>
                {
                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
